name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
    - run: npm run api:test

  check-links:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # run for .md
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      name: 'check-md'
      with:
        file-extension: '.md'
        # only returns errors
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        #location for config (different config to filter out .mdx
        config-file: '.github/workflows/check_broken_link_md_config.json'
        # folders to check parse
        folder-path: 'pages/docs, pages/changelogs, pages/guides'
        # depth from folder path
        max-depth: -1
        # only check files changed in the PR
        # check-modified-files-only: 'yes'
        # branch to compare for diff
        # base-branch: 'main'


    # run for .mdx
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      name: 'check-mdx'
      if: '!cancelled()'
      with:
        file-extension: '.mdx'
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        #location for config (different config to filter out .md
        config-file: '.github/workflows/check_broken_link_mdx_config.json'
        folder-path: 'pages/docs, pages/changelogs, pages/guides'
        max-depth: -1
        # only check files changed in the PR
        # check-modified-files-only: 'yes'
        # branch to compare for diff
        # base-branch: 'main'
